name: Java CI with Maven

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "Dev, main" ]

jobs:
  build_push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Compilar con Maven (push)
        run: mvn clean install --batch-mode --no-transfer-progress
        id: build_push
      - name: Checkear build de Maven (push)
        run: |
          if [ $? -ne 0 ]; then
            echo "Fallo en el build."
            echo "::set-output name=build_status::failed"
          else
            echo "::set-output name=build_status::success"
          fi
      - name: Funcion贸 todo! (push)
        run: echo "Felicitaciones a quien haya pusheado esto!"


  build_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Compilar con Maven (pull request)
        run: mvn clean install --batch-mode --no-transfer-progress
        id: build_pull_request
      - name: Checkear build de Maven (pull request)
        run: |
          if [ $? -ne 0 ]; then
            echo "Fallo en el build."
            echo "::set-output name=build_status::failed"
          else
            echo "::set-output name=build_status::success"
          fi
      - name: Agregar comentario de error al PR
        uses: actions/github-script@v4
        if: ${{ needs.build_pull_request.outputs.build_status == 'failed' }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `El build fall贸. Por favor, revisar el log de la acci贸n.`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
      - name: Funcion贸 todo! (pull request)
        run: echo "Felicitaciones a quien haya pusheado esto!"
